name: Selenium UI Test on .NET 6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: SeleniumIDE

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Install ChromeDriver v137 (match local)
      run: |
    if (-Not (Test-Path "drivers")) { New-Item -ItemType Directory -Path "drivers" }
    Invoke-WebRequest https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.70/win64/chromedriver-win64.zip -OutFile drivers\chromedriver.zip
    Expand-Archive drivers\chromedriver.zip -DestinationPath drivers
    Remove-Item drivers\chromedriver.zip

    - name: Run Selenium Tests
      run: dotnet test --no-build --verbosity normal
